### ISSUE TITLE
nemo outputs

### ISSUE THREAD

**Issue by DrK-Lo** [kjgilbert/aNEMOne#1]
Hey Kim,
I'm getting ready to do some Nemo simulations with neutral loci and quantitative trait loci.  I was wondering whether you had some scripts that convert the different output files for each type into a single file for analysis?

**Comment by kjgilbert** [comment]
Hey Katie, hm I never got an email notification about this post so sorry about the delayed response!

You mean you want to combine an individual's neutral loci with deleterious and quantitative trait loci? (across rows for an individual?) I don't have any scripts that do that. I have a few functions scattered around in odd scripts to trim the Nemo FSTAT output format into the proper FSTAT format if that helps?

**Comment by DrK-Lo** [comment]
OK no worries- just checking!

**Comment by kjgilbert** [comment]
If I add something like that I'll let you know!
